//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDiskont_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersData()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int OrderDataID { get; set; }
        public string FullName { get; set; }
        public string Company { get; set; }
        public int DeliveryMethodID { get; set; }
        public string DeliveryAddress { get; set; }
        public string City { get; set; }
    
        public virtual DeliveryMethods DeliveryMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
