export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INIT_ITEMS = 'INIT_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';
export const CHANGE_ITEM_SIZE = 'CHANGE_ITEM_SIZE';

export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_ERROR_FALSE = 'SET_ERROR_FALSE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
